// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackageHead.proto

package com.bfd.kafka.protobuf;

public final class QMDPPackageHead {
  private QMDPPackageHead() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PackageHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * TNO
     * </pre>
     *
     * <code>optional uint64 dwTNO = 1;</code>
     */
    boolean hasDwTNO();
    /**
     * <pre>
     * TNO
     * </pre>
     *
     * <code>optional uint64 dwTNO = 1;</code>
     */
    long getDwTNO();

    /**
     * <pre>
     * 设备编号
     * </pre>
     *
     * <code>optional uint64 nDevice_ID = 2;</code>
     */
    boolean hasNDeviceID();
    /**
     * <pre>
     * 设备编号
     * </pre>
     *
     * <code>optional uint64 nDevice_ID = 2;</code>
     */
    long getNDeviceID();

    /**
     * <pre>
     * 主消息ID
     * </pre>
     *
     * <code>optional bytes bMessageID = 3;</code>
     */
    boolean hasBMessageID();
    /**
     * <pre>
     * 主消息ID
     * </pre>
     *
     * <code>optional bytes bMessageID = 3;</code>
     */
    com.google.protobuf.ByteString getBMessageID();

    /**
     * <pre>
     * 主消息内容
     * </pre>
     *
     * <code>optional bytes bMessageBody = 4;</code>
     */
    boolean hasBMessageBody();
    /**
     * <pre>
     * 主消息内容
     * </pre>
     *
     * <code>optional bytes bMessageBody = 4;</code>
     */
    com.google.protobuf.ByteString getBMessageBody();

    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    java.util.List<QMDPPackageHead.PackageHead.MessageList> 
        getMessageListList();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    QMDPPackageHead.PackageHead.MessageList getMessageList(int index);
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    int getMessageListCount();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    java.util.List<? extends QMDPPackageHead.PackageHead.MessageListOrBuilder> 
        getMessageListOrBuilderList();
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    QMDPPackageHead.PackageHead.MessageListOrBuilder getMessageListOrBuilder(
        int index);

    /**
     * <pre>
     * 预留字段
     * </pre>
     *
     * <code>optional bytes dwCustomer = 6;</code>
     */
    boolean hasDwCustomer();
    /**
     * <pre>
     * 预留字段
     * </pre>
     *
     * <code>optional bytes dwCustomer = 6;</code>
     */
    com.google.protobuf.ByteString getDwCustomer();

    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>optional uint32 dwSerialNo = 7;</code>
     */
    boolean hasDwSerialNo();
    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>optional uint32 dwSerialNo = 7;</code>
     */
    int getDwSerialNo();

    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>optional bytes bytesProtoVersion = 8;</code>
     */
    boolean hasBytesProtoVersion();
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>optional bytes bytesProtoVersion = 8;</code>
     */
    com.google.protobuf.ByteString getBytesProtoVersion();

    /**
     * <pre>
     * 补报
     * </pre>
     *
     * <code>optional uint32 nSupplement = 9;</code>
     */
    boolean hasNSupplement();
    /**
     * <pre>
     * 补报
     * </pre>
     *
     * <code>optional uint32 nSupplement = 9;</code>
     */
    int getNSupplement();

    /**
     * <pre>
     * VIN
     * </pre>
     *
     * <code>optional bytes bVIN = 10;</code>
     */
    boolean hasBVIN();
    /**
     * <pre>
     * VIN
     * </pre>
     *
     * <code>optional bytes bVIN = 10;</code>
     */
    com.google.protobuf.ByteString getBVIN();

    /**
     * <pre>
     * 预留1
     * </pre>
     *
     * <code>optional bytes bReserved1 = 11;</code>
     */
    boolean hasBReserved1();
    /**
     * <pre>
     * 预留1
     * </pre>
     *
     * <code>optional bytes bReserved1 = 11;</code>
     */
    com.google.protobuf.ByteString getBReserved1();

    /**
     * <pre>
     * 预留2
     * </pre>
     *
     * <code>optional bytes bReserved2 = 12;</code>
     */
    boolean hasBReserved2();
    /**
     * <pre>
     * 预留2
     * </pre>
     *
     * <code>optional bytes bReserved2 = 12;</code>
     */
    com.google.protobuf.ByteString getBReserved2();

    /**
     * <pre>
     * 预留3
     * </pre>
     *
     * <code>optional bytes bReserved3 = 13;</code>
     */
    boolean hasBReserved3();
    /**
     * <pre>
     * 预留3
     * </pre>
     *
     * <code>optional bytes bReserved3 = 13;</code>
     */
    com.google.protobuf.ByteString getBReserved3();
  }
  /**
   * Protobuf type {@code PackageHead}
   */
  public  static final class PackageHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PackageHead)
      PackageHeadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageHead.newBuilder() to construct.
    private PackageHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageHead() {
      dwTNO_ = 0L;
      nDeviceID_ = 0L;
      bMessageID_ = com.google.protobuf.ByteString.EMPTY;
      bMessageBody_ = com.google.protobuf.ByteString.EMPTY;
      messageList_ = java.util.Collections.emptyList();
      dwCustomer_ = com.google.protobuf.ByteString.EMPTY;
      dwSerialNo_ = 0;
      bytesProtoVersion_ = com.google.protobuf.ByteString.EMPTY;
      nSupplement_ = 0;
      bVIN_ = com.google.protobuf.ByteString.EMPTY;
      bReserved1_ = com.google.protobuf.ByteString.EMPTY;
      bReserved2_ = com.google.protobuf.ByteString.EMPTY;
      bReserved3_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              dwTNO_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nDeviceID_ = input.readUInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              bMessageID_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bMessageBody_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                messageList_ = new java.util.ArrayList<QMDPPackageHead.PackageHead.MessageList>();
                mutable_bitField0_ |= 0x00000010;
              }
              messageList_.add(
                  input.readMessage(QMDPPackageHead.PackageHead.MessageList.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              dwCustomer_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              dwSerialNo_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              bytesProtoVersion_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              nSupplement_ = input.readUInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000100;
              bVIN_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000200;
              bReserved1_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000400;
              bReserved2_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00000800;
              bReserved3_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          messageList_ = java.util.Collections.unmodifiableList(messageList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QMDPPackageHead.internal_static_PackageHead_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QMDPPackageHead.internal_static_PackageHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QMDPPackageHead.PackageHead.class, QMDPPackageHead.PackageHead.Builder.class);
    }

    public interface MessageListOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PackageHead.MessageList)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>optional bytes bMsgID = 1;</code>
       */
      boolean hasBMsgID();
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>optional bytes bMsgID = 1;</code>
       */
      com.google.protobuf.ByteString getBMsgID();

      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes bMsgBody = 2;</code>
       */
      boolean hasBMsgBody();
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes bMsgBody = 2;</code>
       */
      com.google.protobuf.ByteString getBMsgBody();
    }
    /**
     * Protobuf type {@code PackageHead.MessageList}
     */
    public  static final class MessageList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:PackageHead.MessageList)
        MessageListOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use MessageList.newBuilder() to construct.
      private MessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private MessageList() {
        bMsgID_ = com.google.protobuf.ByteString.EMPTY;
        bMsgBody_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private MessageList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                bitField0_ |= 0x00000001;
                bMsgID_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                bMsgBody_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QMDPPackageHead.internal_static_PackageHead_MessageList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QMDPPackageHead.internal_static_PackageHead_MessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QMDPPackageHead.PackageHead.MessageList.class, QMDPPackageHead.PackageHead.MessageList.Builder.class);
      }

      private int bitField0_;
      public static final int BMSGID_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString bMsgID_;
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>optional bytes bMsgID = 1;</code>
       */
      public boolean hasBMsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * 消息ID
       * </pre>
       *
       * <code>optional bytes bMsgID = 1;</code>
       */
      public com.google.protobuf.ByteString getBMsgID() {
        return bMsgID_;
      }

      public static final int BMSGBODY_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString bMsgBody_;
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes bMsgBody = 2;</code>
       */
      public boolean hasBMsgBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 消息内容
       * </pre>
       *
       * <code>optional bytes bMsgBody = 2;</code>
       */
      public com.google.protobuf.ByteString getBMsgBody() {
        return bMsgBody_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, bMsgID_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, bMsgBody_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, bMsgID_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, bMsgBody_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof QMDPPackageHead.PackageHead.MessageList)) {
          return super.equals(obj);
        }
        QMDPPackageHead.PackageHead.MessageList other = (QMDPPackageHead.PackageHead.MessageList) obj;

        boolean result = true;
        result = result && (hasBMsgID() == other.hasBMsgID());
        if (hasBMsgID()) {
          result = result && getBMsgID()
              .equals(other.getBMsgID());
        }
        result = result && (hasBMsgBody() == other.hasBMsgBody());
        if (hasBMsgBody()) {
          result = result && getBMsgBody()
              .equals(other.getBMsgBody());
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasBMsgID()) {
          hash = (37 * hash) + BMSGID_FIELD_NUMBER;
          hash = (53 * hash) + getBMsgID().hashCode();
        }
        if (hasBMsgBody()) {
          hash = (37 * hash) + BMSGBODY_FIELD_NUMBER;
          hash = (53 * hash) + getBMsgBody().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static QMDPPackageHead.PackageHead.MessageList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(QMDPPackageHead.PackageHead.MessageList prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PackageHead.MessageList}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PackageHead.MessageList)
          QMDPPackageHead.PackageHead.MessageListOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return QMDPPackageHead.internal_static_PackageHead_MessageList_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return QMDPPackageHead.internal_static_PackageHead_MessageList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  QMDPPackageHead.PackageHead.MessageList.class, QMDPPackageHead.PackageHead.MessageList.Builder.class);
        }

        // Construct using QMDPPackageHead.PackageHead.MessageList.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bMsgID_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          bMsgBody_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return QMDPPackageHead.internal_static_PackageHead_MessageList_descriptor;
        }

        @java.lang.Override
        public QMDPPackageHead.PackageHead.MessageList getDefaultInstanceForType() {
          return QMDPPackageHead.PackageHead.MessageList.getDefaultInstance();
        }

        @java.lang.Override
        public QMDPPackageHead.PackageHead.MessageList build() {
          QMDPPackageHead.PackageHead.MessageList result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public QMDPPackageHead.PackageHead.MessageList buildPartial() {
          QMDPPackageHead.PackageHead.MessageList result = new QMDPPackageHead.PackageHead.MessageList(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.bMsgID_ = bMsgID_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.bMsgBody_ = bMsgBody_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof QMDPPackageHead.PackageHead.MessageList) {
            return mergeFrom((QMDPPackageHead.PackageHead.MessageList)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(QMDPPackageHead.PackageHead.MessageList other) {
          if (other == QMDPPackageHead.PackageHead.MessageList.getDefaultInstance()) return this;
          if (other.hasBMsgID()) {
            setBMsgID(other.getBMsgID());
          }
          if (other.hasBMsgBody()) {
            setBMsgBody(other.getBMsgBody());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          QMDPPackageHead.PackageHead.MessageList parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (QMDPPackageHead.PackageHead.MessageList) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString bMsgID_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         * 消息ID
         * </pre>
         *
         * <code>optional bytes bMsgID = 1;</code>
         */
        public boolean hasBMsgID() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <pre>
         * 消息ID
         * </pre>
         *
         * <code>optional bytes bMsgID = 1;</code>
         */
        public com.google.protobuf.ByteString getBMsgID() {
          return bMsgID_;
        }
        /**
         * <pre>
         * 消息ID
         * </pre>
         *
         * <code>optional bytes bMsgID = 1;</code>
         */
        public Builder setBMsgID(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          bMsgID_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 消息ID
         * </pre>
         *
         * <code>optional bytes bMsgID = 1;</code>
         */
        public Builder clearBMsgID() {
          bitField0_ = (bitField0_ & ~0x00000001);
          bMsgID_ = getDefaultInstance().getBMsgID();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString bMsgBody_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>optional bytes bMsgBody = 2;</code>
         */
        public boolean hasBMsgBody() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>optional bytes bMsgBody = 2;</code>
         */
        public com.google.protobuf.ByteString getBMsgBody() {
          return bMsgBody_;
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>optional bytes bMsgBody = 2;</code>
         */
        public Builder setBMsgBody(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          bMsgBody_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 消息内容
         * </pre>
         *
         * <code>optional bytes bMsgBody = 2;</code>
         */
        public Builder clearBMsgBody() {
          bitField0_ = (bitField0_ & ~0x00000002);
          bMsgBody_ = getDefaultInstance().getBMsgBody();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:PackageHead.MessageList)
      }

      // @@protoc_insertion_point(class_scope:PackageHead.MessageList)
      private static final QMDPPackageHead.PackageHead.MessageList DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new QMDPPackageHead.PackageHead.MessageList();
      }

      public static QMDPPackageHead.PackageHead.MessageList getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageList>
          PARSER = new com.google.protobuf.AbstractParser<MessageList>() {
        @java.lang.Override
        public MessageList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageList(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<MessageList> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<MessageList> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public QMDPPackageHead.PackageHead.MessageList getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int DWTNO_FIELD_NUMBER = 1;
    private long dwTNO_;
    /**
     * <pre>
     * TNO
     * </pre>
     *
     * <code>optional uint64 dwTNO = 1;</code>
     */
    public boolean hasDwTNO() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * TNO
     * </pre>
     *
     * <code>optional uint64 dwTNO = 1;</code>
     */
    public long getDwTNO() {
      return dwTNO_;
    }

    public static final int NDEVICE_ID_FIELD_NUMBER = 2;
    private long nDeviceID_;
    /**
     * <pre>
     * 设备编号
     * </pre>
     *
     * <code>optional uint64 nDevice_ID = 2;</code>
     */
    public boolean hasNDeviceID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 设备编号
     * </pre>
     *
     * <code>optional uint64 nDevice_ID = 2;</code>
     */
    public long getNDeviceID() {
      return nDeviceID_;
    }

    public static final int BMESSAGEID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bMessageID_;
    /**
     * <pre>
     * 主消息ID
     * </pre>
     *
     * <code>optional bytes bMessageID = 3;</code>
     */
    public boolean hasBMessageID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 主消息ID
     * </pre>
     *
     * <code>optional bytes bMessageID = 3;</code>
     */
    public com.google.protobuf.ByteString getBMessageID() {
      return bMessageID_;
    }

    public static final int BMESSAGEBODY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bMessageBody_;
    /**
     * <pre>
     * 主消息内容
     * </pre>
     *
     * <code>optional bytes bMessageBody = 4;</code>
     */
    public boolean hasBMessageBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * 主消息内容
     * </pre>
     *
     * <code>optional bytes bMessageBody = 4;</code>
     */
    public com.google.protobuf.ByteString getBMessageBody() {
      return bMessageBody_;
    }

    public static final int MESSAGELIST_FIELD_NUMBER = 5;
    private java.util.List<QMDPPackageHead.PackageHead.MessageList> messageList_;
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    public java.util.List<QMDPPackageHead.PackageHead.MessageList> getMessageListList() {
      return messageList_;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    public java.util.List<? extends QMDPPackageHead.PackageHead.MessageListOrBuilder> 
        getMessageListOrBuilderList() {
      return messageList_;
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    public int getMessageListCount() {
      return messageList_.size();
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    public QMDPPackageHead.PackageHead.MessageList getMessageList(int index) {
      return messageList_.get(index);
    }
    /**
     * <pre>
     * 消息列表
     * </pre>
     *
     * <code>repeated .PackageHead.MessageList messageList = 5;</code>
     */
    public QMDPPackageHead.PackageHead.MessageListOrBuilder getMessageListOrBuilder(
        int index) {
      return messageList_.get(index);
    }

    public static final int DWCUSTOMER_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString dwCustomer_;
    /**
     * <pre>
     * 预留字段
     * </pre>
     *
     * <code>optional bytes dwCustomer = 6;</code>
     */
    public boolean hasDwCustomer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     * 预留字段
     * </pre>
     *
     * <code>optional bytes dwCustomer = 6;</code>
     */
    public com.google.protobuf.ByteString getDwCustomer() {
      return dwCustomer_;
    }

    public static final int DWSERIALNO_FIELD_NUMBER = 7;
    private int dwSerialNo_;
    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>optional uint32 dwSerialNo = 7;</code>
     */
    public boolean hasDwSerialNo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     * 序列号
     * </pre>
     *
     * <code>optional uint32 dwSerialNo = 7;</code>
     */
    public int getDwSerialNo() {
      return dwSerialNo_;
    }

    public static final int BYTESPROTOVERSION_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString bytesProtoVersion_;
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>optional bytes bytesProtoVersion = 8;</code>
     */
    public boolean hasBytesProtoVersion() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>optional bytes bytesProtoVersion = 8;</code>
     */
    public com.google.protobuf.ByteString getBytesProtoVersion() {
      return bytesProtoVersion_;
    }

    public static final int NSUPPLEMENT_FIELD_NUMBER = 9;
    private int nSupplement_;
    /**
     * <pre>
     * 补报
     * </pre>
     *
     * <code>optional uint32 nSupplement = 9;</code>
     */
    public boolean hasNSupplement() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * 补报
     * </pre>
     *
     * <code>optional uint32 nSupplement = 9;</code>
     */
    public int getNSupplement() {
      return nSupplement_;
    }

    public static final int BVIN_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString bVIN_;
    /**
     * <pre>
     * VIN
     * </pre>
     *
     * <code>optional bytes bVIN = 10;</code>
     */
    public boolean hasBVIN() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * VIN
     * </pre>
     *
     * <code>optional bytes bVIN = 10;</code>
     */
    public com.google.protobuf.ByteString getBVIN() {
      return bVIN_;
    }

    public static final int BRESERVED1_FIELD_NUMBER = 11;
    private com.google.protobuf.ByteString bReserved1_;
    /**
     * <pre>
     * 预留1
     * </pre>
     *
     * <code>optional bytes bReserved1 = 11;</code>
     */
    public boolean hasBReserved1() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     * 预留1
     * </pre>
     *
     * <code>optional bytes bReserved1 = 11;</code>
     */
    public com.google.protobuf.ByteString getBReserved1() {
      return bReserved1_;
    }

    public static final int BRESERVED2_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString bReserved2_;
    /**
     * <pre>
     * 预留2
     * </pre>
     *
     * <code>optional bytes bReserved2 = 12;</code>
     */
    public boolean hasBReserved2() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <pre>
     * 预留2
     * </pre>
     *
     * <code>optional bytes bReserved2 = 12;</code>
     */
    public com.google.protobuf.ByteString getBReserved2() {
      return bReserved2_;
    }

    public static final int BRESERVED3_FIELD_NUMBER = 13;
    private com.google.protobuf.ByteString bReserved3_;
    /**
     * <pre>
     * 预留3
     * </pre>
     *
     * <code>optional bytes bReserved3 = 13;</code>
     */
    public boolean hasBReserved3() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <pre>
     * 预留3
     * </pre>
     *
     * <code>optional bytes bReserved3 = 13;</code>
     */
    public com.google.protobuf.ByteString getBReserved3() {
      return bReserved3_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, dwTNO_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, nDeviceID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, bMessageID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, bMessageBody_);
      }
      for (int i = 0; i < messageList_.size(); i++) {
        output.writeMessage(5, messageList_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, dwCustomer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(7, dwSerialNo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, bytesProtoVersion_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(9, nSupplement_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(10, bVIN_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(11, bReserved1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(12, bReserved2_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(13, bReserved3_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, dwTNO_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, nDeviceID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, bMessageID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, bMessageBody_);
      }
      for (int i = 0; i < messageList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, messageList_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, dwCustomer_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, dwSerialNo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, bytesProtoVersion_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, nSupplement_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, bVIN_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, bReserved1_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, bReserved2_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, bReserved3_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QMDPPackageHead.PackageHead)) {
        return super.equals(obj);
      }
      QMDPPackageHead.PackageHead other = (QMDPPackageHead.PackageHead) obj;

      boolean result = true;
      result = result && (hasDwTNO() == other.hasDwTNO());
      if (hasDwTNO()) {
        result = result && (getDwTNO()
            == other.getDwTNO());
      }
      result = result && (hasNDeviceID() == other.hasNDeviceID());
      if (hasNDeviceID()) {
        result = result && (getNDeviceID()
            == other.getNDeviceID());
      }
      result = result && (hasBMessageID() == other.hasBMessageID());
      if (hasBMessageID()) {
        result = result && getBMessageID()
            .equals(other.getBMessageID());
      }
      result = result && (hasBMessageBody() == other.hasBMessageBody());
      if (hasBMessageBody()) {
        result = result && getBMessageBody()
            .equals(other.getBMessageBody());
      }
      result = result && getMessageListList()
          .equals(other.getMessageListList());
      result = result && (hasDwCustomer() == other.hasDwCustomer());
      if (hasDwCustomer()) {
        result = result && getDwCustomer()
            .equals(other.getDwCustomer());
      }
      result = result && (hasDwSerialNo() == other.hasDwSerialNo());
      if (hasDwSerialNo()) {
        result = result && (getDwSerialNo()
            == other.getDwSerialNo());
      }
      result = result && (hasBytesProtoVersion() == other.hasBytesProtoVersion());
      if (hasBytesProtoVersion()) {
        result = result && getBytesProtoVersion()
            .equals(other.getBytesProtoVersion());
      }
      result = result && (hasNSupplement() == other.hasNSupplement());
      if (hasNSupplement()) {
        result = result && (getNSupplement()
            == other.getNSupplement());
      }
      result = result && (hasBVIN() == other.hasBVIN());
      if (hasBVIN()) {
        result = result && getBVIN()
            .equals(other.getBVIN());
      }
      result = result && (hasBReserved1() == other.hasBReserved1());
      if (hasBReserved1()) {
        result = result && getBReserved1()
            .equals(other.getBReserved1());
      }
      result = result && (hasBReserved2() == other.hasBReserved2());
      if (hasBReserved2()) {
        result = result && getBReserved2()
            .equals(other.getBReserved2());
      }
      result = result && (hasBReserved3() == other.hasBReserved3());
      if (hasBReserved3()) {
        result = result && getBReserved3()
            .equals(other.getBReserved3());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDwTNO()) {
        hash = (37 * hash) + DWTNO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDwTNO());
      }
      if (hasNDeviceID()) {
        hash = (37 * hash) + NDEVICE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNDeviceID());
      }
      if (hasBMessageID()) {
        hash = (37 * hash) + BMESSAGEID_FIELD_NUMBER;
        hash = (53 * hash) + getBMessageID().hashCode();
      }
      if (hasBMessageBody()) {
        hash = (37 * hash) + BMESSAGEBODY_FIELD_NUMBER;
        hash = (53 * hash) + getBMessageBody().hashCode();
      }
      if (getMessageListCount() > 0) {
        hash = (37 * hash) + MESSAGELIST_FIELD_NUMBER;
        hash = (53 * hash) + getMessageListList().hashCode();
      }
      if (hasDwCustomer()) {
        hash = (37 * hash) + DWCUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getDwCustomer().hashCode();
      }
      if (hasDwSerialNo()) {
        hash = (37 * hash) + DWSERIALNO_FIELD_NUMBER;
        hash = (53 * hash) + getDwSerialNo();
      }
      if (hasBytesProtoVersion()) {
        hash = (37 * hash) + BYTESPROTOVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getBytesProtoVersion().hashCode();
      }
      if (hasNSupplement()) {
        hash = (37 * hash) + NSUPPLEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getNSupplement();
      }
      if (hasBVIN()) {
        hash = (37 * hash) + BVIN_FIELD_NUMBER;
        hash = (53 * hash) + getBVIN().hashCode();
      }
      if (hasBReserved1()) {
        hash = (37 * hash) + BRESERVED1_FIELD_NUMBER;
        hash = (53 * hash) + getBReserved1().hashCode();
      }
      if (hasBReserved2()) {
        hash = (37 * hash) + BRESERVED2_FIELD_NUMBER;
        hash = (53 * hash) + getBReserved2().hashCode();
      }
      if (hasBReserved3()) {
        hash = (37 * hash) + BRESERVED3_FIELD_NUMBER;
        hash = (53 * hash) + getBReserved3().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QMDPPackageHead.PackageHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QMDPPackageHead.PackageHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QMDPPackageHead.PackageHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QMDPPackageHead.PackageHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QMDPPackageHead.PackageHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QMDPPackageHead.PackageHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QMDPPackageHead.PackageHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PackageHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PackageHead)
        QMDPPackageHead.PackageHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QMDPPackageHead.internal_static_PackageHead_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QMDPPackageHead.internal_static_PackageHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QMDPPackageHead.PackageHead.class, QMDPPackageHead.PackageHead.Builder.class);
      }

      // Construct using QMDPPackageHead.PackageHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessageListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dwTNO_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        nDeviceID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        bMessageID_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        bMessageBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          messageListBuilder_.clear();
        }
        dwCustomer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        dwSerialNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        bytesProtoVersion_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        nSupplement_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        bVIN_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        bReserved1_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000400);
        bReserved2_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000800);
        bReserved3_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QMDPPackageHead.internal_static_PackageHead_descriptor;
      }

      @java.lang.Override
      public QMDPPackageHead.PackageHead getDefaultInstanceForType() {
        return QMDPPackageHead.PackageHead.getDefaultInstance();
      }

      @java.lang.Override
      public QMDPPackageHead.PackageHead build() {
        QMDPPackageHead.PackageHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QMDPPackageHead.PackageHead buildPartial() {
        QMDPPackageHead.PackageHead result = new QMDPPackageHead.PackageHead(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dwTNO_ = dwTNO_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nDeviceID_ = nDeviceID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bMessageID_ = bMessageID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bMessageBody_ = bMessageBody_;
        if (messageListBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            messageList_ = java.util.Collections.unmodifiableList(messageList_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.messageList_ = messageList_;
        } else {
          result.messageList_ = messageListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dwCustomer_ = dwCustomer_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dwSerialNo_ = dwSerialNo_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bytesProtoVersion_ = bytesProtoVersion_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.nSupplement_ = nSupplement_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000100;
        }
        result.bVIN_ = bVIN_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000200;
        }
        result.bReserved1_ = bReserved1_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000400;
        }
        result.bReserved2_ = bReserved2_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.bReserved3_ = bReserved3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QMDPPackageHead.PackageHead) {
          return mergeFrom((QMDPPackageHead.PackageHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QMDPPackageHead.PackageHead other) {
        if (other == QMDPPackageHead.PackageHead.getDefaultInstance()) return this;
        if (other.hasDwTNO()) {
          setDwTNO(other.getDwTNO());
        }
        if (other.hasNDeviceID()) {
          setNDeviceID(other.getNDeviceID());
        }
        if (other.hasBMessageID()) {
          setBMessageID(other.getBMessageID());
        }
        if (other.hasBMessageBody()) {
          setBMessageBody(other.getBMessageBody());
        }
        if (messageListBuilder_ == null) {
          if (!other.messageList_.isEmpty()) {
            if (messageList_.isEmpty()) {
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMessageListIsMutable();
              messageList_.addAll(other.messageList_);
            }
            onChanged();
          }
        } else {
          if (!other.messageList_.isEmpty()) {
            if (messageListBuilder_.isEmpty()) {
              messageListBuilder_.dispose();
              messageListBuilder_ = null;
              messageList_ = other.messageList_;
              bitField0_ = (bitField0_ & ~0x00000010);
              messageListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageListFieldBuilder() : null;
            } else {
              messageListBuilder_.addAllMessages(other.messageList_);
            }
          }
        }
        if (other.hasDwCustomer()) {
          setDwCustomer(other.getDwCustomer());
        }
        if (other.hasDwSerialNo()) {
          setDwSerialNo(other.getDwSerialNo());
        }
        if (other.hasBytesProtoVersion()) {
          setBytesProtoVersion(other.getBytesProtoVersion());
        }
        if (other.hasNSupplement()) {
          setNSupplement(other.getNSupplement());
        }
        if (other.hasBVIN()) {
          setBVIN(other.getBVIN());
        }
        if (other.hasBReserved1()) {
          setBReserved1(other.getBReserved1());
        }
        if (other.hasBReserved2()) {
          setBReserved2(other.getBReserved2());
        }
        if (other.hasBReserved3()) {
          setBReserved3(other.getBReserved3());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QMDPPackageHead.PackageHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QMDPPackageHead.PackageHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long dwTNO_ ;
      /**
       * <pre>
       * TNO
       * </pre>
       *
       * <code>optional uint64 dwTNO = 1;</code>
       */
      public boolean hasDwTNO() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * TNO
       * </pre>
       *
       * <code>optional uint64 dwTNO = 1;</code>
       */
      public long getDwTNO() {
        return dwTNO_;
      }
      /**
       * <pre>
       * TNO
       * </pre>
       *
       * <code>optional uint64 dwTNO = 1;</code>
       */
      public Builder setDwTNO(long value) {
        bitField0_ |= 0x00000001;
        dwTNO_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * TNO
       * </pre>
       *
       * <code>optional uint64 dwTNO = 1;</code>
       */
      public Builder clearDwTNO() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dwTNO_ = 0L;
        onChanged();
        return this;
      }

      private long nDeviceID_ ;
      /**
       * <pre>
       * 设备编号
       * </pre>
       *
       * <code>optional uint64 nDevice_ID = 2;</code>
       */
      public boolean hasNDeviceID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 设备编号
       * </pre>
       *
       * <code>optional uint64 nDevice_ID = 2;</code>
       */
      public long getNDeviceID() {
        return nDeviceID_;
      }
      /**
       * <pre>
       * 设备编号
       * </pre>
       *
       * <code>optional uint64 nDevice_ID = 2;</code>
       */
      public Builder setNDeviceID(long value) {
        bitField0_ |= 0x00000002;
        nDeviceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备编号
       * </pre>
       *
       * <code>optional uint64 nDevice_ID = 2;</code>
       */
      public Builder clearNDeviceID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nDeviceID_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bMessageID_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 主消息ID
       * </pre>
       *
       * <code>optional bytes bMessageID = 3;</code>
       */
      public boolean hasBMessageID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * 主消息ID
       * </pre>
       *
       * <code>optional bytes bMessageID = 3;</code>
       */
      public com.google.protobuf.ByteString getBMessageID() {
        return bMessageID_;
      }
      /**
       * <pre>
       * 主消息ID
       * </pre>
       *
       * <code>optional bytes bMessageID = 3;</code>
       */
      public Builder setBMessageID(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bMessageID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 主消息ID
       * </pre>
       *
       * <code>optional bytes bMessageID = 3;</code>
       */
      public Builder clearBMessageID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bMessageID_ = getDefaultInstance().getBMessageID();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bMessageBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 主消息内容
       * </pre>
       *
       * <code>optional bytes bMessageBody = 4;</code>
       */
      public boolean hasBMessageBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * 主消息内容
       * </pre>
       *
       * <code>optional bytes bMessageBody = 4;</code>
       */
      public com.google.protobuf.ByteString getBMessageBody() {
        return bMessageBody_;
      }
      /**
       * <pre>
       * 主消息内容
       * </pre>
       *
       * <code>optional bytes bMessageBody = 4;</code>
       */
      public Builder setBMessageBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bMessageBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 主消息内容
       * </pre>
       *
       * <code>optional bytes bMessageBody = 4;</code>
       */
      public Builder clearBMessageBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bMessageBody_ = getDefaultInstance().getBMessageBody();
        onChanged();
        return this;
      }

      private java.util.List<QMDPPackageHead.PackageHead.MessageList> messageList_ =
        java.util.Collections.emptyList();
      private void ensureMessageListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          messageList_ = new java.util.ArrayList<QMDPPackageHead.PackageHead.MessageList>(messageList_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          QMDPPackageHead.PackageHead.MessageList, QMDPPackageHead.PackageHead.MessageList.Builder, QMDPPackageHead.PackageHead.MessageListOrBuilder> messageListBuilder_;

      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public java.util.List<QMDPPackageHead.PackageHead.MessageList> getMessageListList() {
        if (messageListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messageList_);
        } else {
          return messageListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public int getMessageListCount() {
        if (messageListBuilder_ == null) {
          return messageList_.size();
        } else {
          return messageListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public QMDPPackageHead.PackageHead.MessageList getMessageList(int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);
        } else {
          return messageListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder setMessageList(
          int index, QMDPPackageHead.PackageHead.MessageList value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.set(index, value);
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder setMessageList(
          int index, QMDPPackageHead.PackageHead.MessageList.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder addMessageList(QMDPPackageHead.PackageHead.MessageList value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder addMessageList(
          int index, QMDPPackageHead.PackageHead.MessageList value) {
        if (messageListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageListIsMutable();
          messageList_.add(index, value);
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder addMessageList(
          QMDPPackageHead.PackageHead.MessageList.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder addMessageList(
          int index, QMDPPackageHead.PackageHead.MessageList.Builder builderForValue) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder addAllMessageList(
          java.lang.Iterable<? extends QMDPPackageHead.PackageHead.MessageList> values) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageList_);
          onChanged();
        } else {
          messageListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder clearMessageList() {
        if (messageListBuilder_ == null) {
          messageList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          messageListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public Builder removeMessageList(int index) {
        if (messageListBuilder_ == null) {
          ensureMessageListIsMutable();
          messageList_.remove(index);
          onChanged();
        } else {
          messageListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public QMDPPackageHead.PackageHead.MessageList.Builder getMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public QMDPPackageHead.PackageHead.MessageListOrBuilder getMessageListOrBuilder(
          int index) {
        if (messageListBuilder_ == null) {
          return messageList_.get(index);  } else {
          return messageListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public java.util.List<? extends QMDPPackageHead.PackageHead.MessageListOrBuilder> 
           getMessageListOrBuilderList() {
        if (messageListBuilder_ != null) {
          return messageListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messageList_);
        }
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public QMDPPackageHead.PackageHead.MessageList.Builder addMessageListBuilder() {
        return getMessageListFieldBuilder().addBuilder(
            QMDPPackageHead.PackageHead.MessageList.getDefaultInstance());
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public QMDPPackageHead.PackageHead.MessageList.Builder addMessageListBuilder(
          int index) {
        return getMessageListFieldBuilder().addBuilder(
            index, QMDPPackageHead.PackageHead.MessageList.getDefaultInstance());
      }
      /**
       * <pre>
       * 消息列表
       * </pre>
       *
       * <code>repeated .PackageHead.MessageList messageList = 5;</code>
       */
      public java.util.List<QMDPPackageHead.PackageHead.MessageList.Builder> 
           getMessageListBuilderList() {
        return getMessageListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          QMDPPackageHead.PackageHead.MessageList, QMDPPackageHead.PackageHead.MessageList.Builder, QMDPPackageHead.PackageHead.MessageListOrBuilder> 
          getMessageListFieldBuilder() {
        if (messageListBuilder_ == null) {
          messageListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              QMDPPackageHead.PackageHead.MessageList, QMDPPackageHead.PackageHead.MessageList.Builder, QMDPPackageHead.PackageHead.MessageListOrBuilder>(
                  messageList_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          messageList_ = null;
        }
        return messageListBuilder_;
      }

      private com.google.protobuf.ByteString dwCustomer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 预留字段
       * </pre>
       *
       * <code>optional bytes dwCustomer = 6;</code>
       */
      public boolean hasDwCustomer() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       * 预留字段
       * </pre>
       *
       * <code>optional bytes dwCustomer = 6;</code>
       */
      public com.google.protobuf.ByteString getDwCustomer() {
        return dwCustomer_;
      }
      /**
       * <pre>
       * 预留字段
       * </pre>
       *
       * <code>optional bytes dwCustomer = 6;</code>
       */
      public Builder setDwCustomer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        dwCustomer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留字段
       * </pre>
       *
       * <code>optional bytes dwCustomer = 6;</code>
       */
      public Builder clearDwCustomer() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dwCustomer_ = getDefaultInstance().getDwCustomer();
        onChanged();
        return this;
      }

      private int dwSerialNo_ ;
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>optional uint32 dwSerialNo = 7;</code>
       */
      public boolean hasDwSerialNo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>optional uint32 dwSerialNo = 7;</code>
       */
      public int getDwSerialNo() {
        return dwSerialNo_;
      }
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>optional uint32 dwSerialNo = 7;</code>
       */
      public Builder setDwSerialNo(int value) {
        bitField0_ |= 0x00000040;
        dwSerialNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 序列号
       * </pre>
       *
       * <code>optional uint32 dwSerialNo = 7;</code>
       */
      public Builder clearDwSerialNo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        dwSerialNo_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesProtoVersion_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 协议版本
       * </pre>
       *
       * <code>optional bytes bytesProtoVersion = 8;</code>
       */
      public boolean hasBytesProtoVersion() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * 协议版本
       * </pre>
       *
       * <code>optional bytes bytesProtoVersion = 8;</code>
       */
      public com.google.protobuf.ByteString getBytesProtoVersion() {
        return bytesProtoVersion_;
      }
      /**
       * <pre>
       * 协议版本
       * </pre>
       *
       * <code>optional bytes bytesProtoVersion = 8;</code>
       */
      public Builder setBytesProtoVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        bytesProtoVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 协议版本
       * </pre>
       *
       * <code>optional bytes bytesProtoVersion = 8;</code>
       */
      public Builder clearBytesProtoVersion() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bytesProtoVersion_ = getDefaultInstance().getBytesProtoVersion();
        onChanged();
        return this;
      }

      private int nSupplement_ ;
      /**
       * <pre>
       * 补报
       * </pre>
       *
       * <code>optional uint32 nSupplement = 9;</code>
       */
      public boolean hasNSupplement() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * 补报
       * </pre>
       *
       * <code>optional uint32 nSupplement = 9;</code>
       */
      public int getNSupplement() {
        return nSupplement_;
      }
      /**
       * <pre>
       * 补报
       * </pre>
       *
       * <code>optional uint32 nSupplement = 9;</code>
       */
      public Builder setNSupplement(int value) {
        bitField0_ |= 0x00000100;
        nSupplement_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 补报
       * </pre>
       *
       * <code>optional uint32 nSupplement = 9;</code>
       */
      public Builder clearNSupplement() {
        bitField0_ = (bitField0_ & ~0x00000100);
        nSupplement_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bVIN_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * VIN
       * </pre>
       *
       * <code>optional bytes bVIN = 10;</code>
       */
      public boolean hasBVIN() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       * VIN
       * </pre>
       *
       * <code>optional bytes bVIN = 10;</code>
       */
      public com.google.protobuf.ByteString getBVIN() {
        return bVIN_;
      }
      /**
       * <pre>
       * VIN
       * </pre>
       *
       * <code>optional bytes bVIN = 10;</code>
       */
      public Builder setBVIN(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        bVIN_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * VIN
       * </pre>
       *
       * <code>optional bytes bVIN = 10;</code>
       */
      public Builder clearBVIN() {
        bitField0_ = (bitField0_ & ~0x00000200);
        bVIN_ = getDefaultInstance().getBVIN();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bReserved1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 预留1
       * </pre>
       *
       * <code>optional bytes bReserved1 = 11;</code>
       */
      public boolean hasBReserved1() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <pre>
       * 预留1
       * </pre>
       *
       * <code>optional bytes bReserved1 = 11;</code>
       */
      public com.google.protobuf.ByteString getBReserved1() {
        return bReserved1_;
      }
      /**
       * <pre>
       * 预留1
       * </pre>
       *
       * <code>optional bytes bReserved1 = 11;</code>
       */
      public Builder setBReserved1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        bReserved1_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留1
       * </pre>
       *
       * <code>optional bytes bReserved1 = 11;</code>
       */
      public Builder clearBReserved1() {
        bitField0_ = (bitField0_ & ~0x00000400);
        bReserved1_ = getDefaultInstance().getBReserved1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bReserved2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 预留2
       * </pre>
       *
       * <code>optional bytes bReserved2 = 12;</code>
       */
      public boolean hasBReserved2() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <pre>
       * 预留2
       * </pre>
       *
       * <code>optional bytes bReserved2 = 12;</code>
       */
      public com.google.protobuf.ByteString getBReserved2() {
        return bReserved2_;
      }
      /**
       * <pre>
       * 预留2
       * </pre>
       *
       * <code>optional bytes bReserved2 = 12;</code>
       */
      public Builder setBReserved2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        bReserved2_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留2
       * </pre>
       *
       * <code>optional bytes bReserved2 = 12;</code>
       */
      public Builder clearBReserved2() {
        bitField0_ = (bitField0_ & ~0x00000800);
        bReserved2_ = getDefaultInstance().getBReserved2();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bReserved3_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 预留3
       * </pre>
       *
       * <code>optional bytes bReserved3 = 13;</code>
       */
      public boolean hasBReserved3() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <pre>
       * 预留3
       * </pre>
       *
       * <code>optional bytes bReserved3 = 13;</code>
       */
      public com.google.protobuf.ByteString getBReserved3() {
        return bReserved3_;
      }
      /**
       * <pre>
       * 预留3
       * </pre>
       *
       * <code>optional bytes bReserved3 = 13;</code>
       */
      public Builder setBReserved3(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        bReserved3_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留3
       * </pre>
       *
       * <code>optional bytes bReserved3 = 13;</code>
       */
      public Builder clearBReserved3() {
        bitField0_ = (bitField0_ & ~0x00001000);
        bReserved3_ = getDefaultInstance().getBReserved3();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PackageHead)
    }

    // @@protoc_insertion_point(class_scope:PackageHead)
    private static final QMDPPackageHead.PackageHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QMDPPackageHead.PackageHead();
    }

    public static QMDPPackageHead.PackageHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PackageHead>
        PARSER = new com.google.protobuf.AbstractParser<PackageHead>() {
      @java.lang.Override
      public PackageHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageHead> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QMDPPackageHead.PackageHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PackageHead_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageHead_MessageList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PackageHead_MessageList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PackageHead.proto\"\334\002\n\013PackageHead\022\r\n\005d" +
      "wTNO\030\001 \001(\004\022\022\n\nnDevice_ID\030\002 \001(\004\022\022\n\nbMessa" +
      "geID\030\003 \001(\014\022\024\n\014bMessageBody\030\004 \001(\014\022-\n\013mess" +
      "ageList\030\005 \003(\0132\030.PackageHead.MessageList\022" +
      "\022\n\ndwCustomer\030\006 \001(\014\022\022\n\ndwSerialNo\030\007 \001(\r\022" +
      "\031\n\021bytesProtoVersion\030\010 \001(\014\022\023\n\013nSupplemen" +
      "t\030\t \001(\r\022\014\n\004bVIN\030\n \001(\014\022\022\n\nbReserved1\030\013 \001(" +
      "\014\022\022\n\nbReserved2\030\014 \001(\014\022\022\n\nbReserved3\030\r \001(" +
      "\014\032/\n\013MessageList\022\016\n\006bMsgID\030\001 \001(\014\022\020\n\010bMsg" +
      "Body\030\002 \001(\014B(\n\025com.bfd.kafka.receiveB\017QMD" +
      "PPackageHead"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PackageHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PackageHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PackageHead_descriptor,
        new java.lang.String[] { "DwTNO", "NDeviceID", "BMessageID", "BMessageBody", "MessageList", "DwCustomer", "DwSerialNo", "BytesProtoVersion", "NSupplement", "BVIN", "BReserved1", "BReserved2", "BReserved3", });
    internal_static_PackageHead_MessageList_descriptor =
      internal_static_PackageHead_descriptor.getNestedTypes().get(0);
    internal_static_PackageHead_MessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PackageHead_MessageList_descriptor,
        new java.lang.String[] { "BMsgID", "BMsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
